name: Build
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          curl https://www.sourcemod.net/smdrop/1.11/$(curl --silent https://www.sourcemod.net/smdrop/1.11/sourcemod-latest-linux) -o sourcemod.tar.gz
          tar -xf sourcemod.tar.gz
          git clone https://github.com/Bara/Multi-Colors.git
          mv Multi-Colors/addons/sourcemod/scripting/include/* addons/sourcemod/scripting/include/
          addons/sourcemod/scripting/spcomp64 kaccm.sp
      - uses: actions/upload-artifact@v3
        with:
          name: kaccm.smx
          path: ./kaccm.smx
